services:
  - type: web
    name: bloom-api
    env: node
    plan: free
    buildCommand: npm install && npm --workspace @bloom/api run build
    startCommand: npm --workspace @bloom/api run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MEDIA_STORAGE
        value: local
      - key: LOCAL_MEDIA_DIR
        value: /opt/render/project/src/apps/api/uploads
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: SEED_ADMIN_EMAIL
        sync: false
      - key: SEED_ADMIN_PASSWORD
        sync: false

